-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 08:51:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `a05students` ;

-- -----------------------------------------------------
-- Schema a05students
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a05students` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `a05students` ;

-- -----------------------------------------------------
-- Table `a05students`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a05students`.`courses` ;

CREATE TABLE IF NOT EXISTS `a05students`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `a05students`.`majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a05students`.`majors` ;

CREATE TABLE IF NOT EXISTS `a05students`.`majors` (
  `major_id` INT NOT NULL AUTO_INCREMENT,
  `major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`major_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `a05students`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a05students`.`addresses` ;

CREATE TABLE IF NOT EXISTS `a05students`.`addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `a05students`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a05students`.`students` ;

CREATE TABLE IF NOT EXISTS `a05students`.`students` (
  `student_id` VARCHAR(4) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `major_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_students_addresses`
  FOREIGN KEY (`address_id`)
  REFERENCES `a05students`.`addresses` (`address_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_majors`
  FOREIGN KEY (`major_id`)
  REFERENCES `a05students`.`majors` (`major_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `a05students`.`studentcourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a05students`.`student_course` ;

CREATE TABLE IF NOT EXISTS `a05students`.`student_course` (
  `student_course_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` VARCHAR(4) NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`student_course_id`),
  CONSTRAINT `fk_student_course_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `a05students`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_course_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `a05students`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_student_course_student_idx` ON `a05students`.`student_course` (`student_id` ASC) VISIBLE;

CREATE INDEX `fk_student_course_course_idx` ON `a05students`.`student_course` (`course_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO courses (course) VALUES ('IT1025');
INSERT INTO courses (course) VALUES ('IT1050');
INSERT INTO courses (course) VALUES ('IT1223');

INSERT INTO majors (major) VALUES('Programming');
INSERT INTO majors (major) VALUES('Networking');
INSERT INTO majors (major) VALUES('Art History');

INSERT INTO addresses (address) VALUES('124 Main St.');
INSERT INTO addresses (address) VALUES('345 Second St.');
INSERT INTO addresses (address) VALUES('600 5th Ave.');

INSERT INTO students (student_id, last_name, first_name, address_id, email, major_id) VALUES('S1', 'Smith', 'Joe', 1, 'Joe@school.edu', 3);
INSERT INTO students (student_id, last_name, first_name, address_id, email, major_id) VALUES('S2', 'Brown', 'Sue', 2, 'Sue@school.edu', 2);
INSERT INTO students (student_id, last_name, first_name, address_id, email, major_id) VALUES('S3', 'Green', 'Nick', 3, 'Sue@school.edu', 1);

INSERT INTO student_course (student_id, course_id) VALUES('S1', 3);
INSERT INTO student_course (student_id, course_id) VALUES('S2', 2);
INSERT INTO student_course (student_id, course_id) VALUES('S3', 1);INSERT INTO student_course (student_id, course_id) VALUES('S1', 3);
